services:
  - type: web
    name: fingro-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FIREBASE_CREDENTIALS_PATH
        value: firebase-credentials.json
    files:
      - name: firebase-credentials
        sync: false
        destination: firebase-credentials.json
